from pathlib import Path
from typing import Dict

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def generate_report(user_id: str, comic_id: str, subgrades: Dict[str, float], report_dir: Path) -> Path:
    """Generate a simple one-page PDF grading report."""
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / "grading_report.pdf"

    c = canvas.Canvas(str(report_path), pagesize=letter)
    width, height = letter

    y = height - 72
    c.setFont("Helvetica-Bold", 20)
    c.drawString(72, y, "ComicVault Grading Report")

    y -= 40
    c.setFont("Helvetica", 12)
    c.drawString(72, y, f"User ID: {user_id}")
    y -= 20
    c.drawString(72, y, f"Comic ID: {comic_id}")
    y -= 30

    c.setFont("Helvetica-Bold", 14)
    c.drawString(72, y, "Subgrades:")
    y -= 24
    c.setFont("Helvetica", 12)

    for key in ["corners", "spine", "surface", "centering", "color"]:
        c.drawString(90, y, f"{key.capitalize()}: {subgrades.get(key, 0.0)}")
        y -= 18

    y -= 10
    c.setFont("Helvetica-Bold", 14)
    c.drawString(72, y, f"Final Grade: {subgrades.get('final', 0.0)}")
    y -= 30

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(72, y, "Note: This grade is generated by an automated system and is not a CGC/CGC-verified grade.")
    c.showPage()
    c.save()

    return report_path
